'use client';
//package
import { useState } from 'react';
//slice
import ProfileCardPres from '../presentational/ProfileCardPres';

//type
import { User } from '../types';

export default function ProfileCardCont() {
  const [userData, setUserData] = useState<User>({
    id: 'uuid',
    bg: null,
    profileImg: null,
    name: '유저닉네임',
    info: `안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ...
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    `,
  });
  return <ProfileCardPres userData={userData} />;
}
