'use client';
//package
import { useState } from 'react';
//layer
import ProfileCardPres from '../presentational/ProfileCardPres';

type User = {
  id: string;
  bg: string | null;
  profileImg: string | null;
  name: string;
  info: string | null;
};

export default function ProfileCardCont() {
  const [userData, setUserData] = useState<User>({
    id: 'uuid',
    bg: null,
    profileImg: null,
    name: '유저닉네임',
    info: `안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ...
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    안녕하세요! FE개발자입니다. 현재는 취준생이며 이러한 기술들을 사용중입니다. ... 
    `,
  });
  return <ProfileCardPres userData={userData} />;
}
